export const APP_CONST = {
	MANDATORY_HEADERS_NAME_LIST: ['LOG-TRACKING-ID', 'USER-TYPE', 'CONSUMER-APP-PROCESS', 'PRINCIPAL-ROLE'],
	HEADERS: {
		LOG_TRACKING_ID: 'LOG-TRACKING-ID',
		USER_ID: 'USER-ID',
		USER_TYPE: 'USER-TYPE',
		PRINCIPAL_ROLE: 'PRINCIPAL-ROLE',
		CONSUMER_APP_PROCESS: 'CONSUMER-APP-PROCESS',
	},

	CHAR: {
		COMMA: ',',
		SLASH: '/',
		COLON: ':',
		SEMI_COLON: ';',
		HYPHEN: '-',
		AT: '@',
		UNDERSCORE: '_',
		QUESTION: '?',
		DOT: '.',
	},
	COMMON: {
		DEFAULT_DATE_TIME_FORMAT: 'yyyy-MM-dd HH:mm:ss.SSSS',
		DEFAULT_HOST: '127.0.0.1',
		DEFAULT_PORT: 5000,
		DEFAULT_TZ: 'Asia/Kolkatta',
	},
};
